### PR TITLE
allowed for VenusTestList to be referenced in the proper window context

### PR DESCRIPTION
**Pull request by geoffberger**
Fixes issue where spinner doesn't stop on tests index page. Only applicable to the 2.x branch.

### CODE REVIEW

**Comment by rbakr** [comment]
This is great @geoffberger , can you please add some unit tests to cover this case?

**Comment by geoffberger** [comment]
@rbakr I would be happy to. However, as far as I can tell, we don't have any unit tests for the runner_client, i.e. the client side portion of the project. I wouldn't make it part of this commit, but we need to set things up to allow so. We already discussed this on the side, but it sounds like you'll be taking care of the setup. Once that's in place though, I'll get those going. Thanks!

**Comment by wei-liu** [comment]
For this problem, we may need to use integration test, even selenium test to cover. It may worth the effort to setup. But I would push that to some later time.

**Comment by geoffberger** [comment]
@wei-liu I agree, for a more thorough test, it should be an integration test. Although it's a silly unit test, it should get the job done.

**Comment by rbakr** [comment]
If for some reason the code were to regress to `window.VenusTestList`, we would catch it.  A integration test would be great, but this should help us avoid a regression for now.

**Comment by sethmcl** [comment]
Cool. Looking forward to seeing this merged.  Just a small note on process, it might be good to squash these commits before merging. Thanks!

**Comment by geoffberger** [comment]
The updated pull request can be found here: https://github.com/linkedin/venus.js/pull/354

**Pull request closed without merging**
